workflows:
  ios-build-workflow:
    name: iOS Build
    max_build_duration: 20
    instance_type: mac_mini_m1
    scripts:
      - name: Build with Xcode
        script: |
          xcodebuild -workspace "Wispwood.xcworkspace" -scheme "Wispwood" -sdk iphoneos archive -archivePath $PWD/build/Wispwood.xcarchive
