workflows:
  ios-unity-build:
    name: Unity iOS Build

    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      unity: 6000.0.67f1

    scripts:
      - name: Verify Unity project
        script: |
          ls
          test -d Assets
          test -d ProjectSettings

      - name: Build iOS Xcode project
        script: |
          unity-editor \
            -batchmode \
            -quit \
            -projectPath . \
            -buildTarget iOS

      - name: Find Xcode project
        script: |
          find . -name "*.xcodeproj"

      - name: Build IPA
        script: |
          cd build/ios

          xcodebuild \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            archive \
            -archivePath $PWD/App.xcarchive

    artifacts:
      - "**/*.ipa"
      - "**/*.xcarchive"
