default_platform(:ios)

platform :ios do
  lane :build_only do
    # هَادَا غِيرْ لْـ Build، بْلَا Metadata
    gym(scheme: "Wispwood") # عَدَّلْ "Wispwood" بـ Scheme د اللَّعْبَة دْيَالْكْ
  end
end
