default_platform(:ios)

platform :ios do
  desc "Test Metadata & Screenshots Upload"
  lane :upload_meta_test do
    deliver(
      app_identifier: "650392847",
      submit_for_review: false,
      skip_binary_upload: true,
      force: true
    )
  end
end
